spring:
  application:
    name: coder-test-backend
  datasource:
    driver-class-name: # <todo> 待生成
    url: # <todo> url 地址待生成
    username: root
    password: 123456
server:
  port: 8123
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      # 逻辑删除
      logic-delete-field: isDelete
# springdoc-openapi项目配置
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      # 这里改成自己的接口类包名
      packages-to-scan: com.example.backend.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
